### ISSUE TITLE
using as mixin with composite view

### ISSUE THREAD

**Issue by heyandie** [orangain/marionette-sortable#2]
Hi. I tried to use this a behavior mixin with my composite view and I am getting this error.

``` javascript
this.getChildViewContainer(...).sortable is not a function
```

**Comment by heyandie** [comment]
I got it. It was a dependency problem with jquery-ui. I am using require.js so I used the shim to properly declare jquery-ui dependency for marionette-sortable. Thank you.

**Comment by orangain** [comment]
Yes, as the marionette-sortable requires either jquery-ui-sortable or html5-sortable, it does not declare dependency for them. You need to choose and load one or other of two.
